In [1]:
import numpy as np

In [3]:
'''
Imagine you’re a teacher and you need to keep track of your student’s test scores. On the first test, the students received the following scores:
92, 94, 88, 91, 87
Create a NumPy array with these values and save it with the name test_1.
'''

test1 = np.array([92, 94, 88, 91, 87])
test1

array([92, 94, 88, 91, 87])

In [4]:
#Most of the times, we usually get the values from a file. Numpy gives
#a function called genfromtxt which delimeter as a paramter thro which
#we can import the data into a numpy array

test2 = np.genfromtxt('samplefile.csv',delimiter=',') #you can use any other delimeter that seperates the values
print(test2)

[10. 20. 30. 40. 50.]


In [5]:
#So what makes Numpy so special, it eliminates the use of for loop
'''
If we wanted to add 3 to each element of the list in python
list1 = [1,3,4,5]
list_add_3 = []
for i in range(len(list1)):
  list_add_3.append(list1[i] + 3)
'''
#The same above code in numpy would become
list1 = [1,3,4,5]
nplist1 = np.array(list1)
nplist1 = nplist1 +3 #This is the element row wise operation.
#We can do the same thing for all mathematical operations
print(nplist1)

[4 6 7 8]


In [7]:
#Similarly we can do any mathematical operation the numpy arrays together if they are of equal length

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
'''
Let’s find the average of each student’s test scores to calculate their final
grade for the semester. Start by adding the three arrays together and
save the answer to the variable total_grade.
'''
total_grade = test_1 + test_2 + test_3
total_grade

array([258, 279, 246, 274, 270])

In [8]:
'''
Now, divide total_grade by the number of tests taken to find the average score
for each student. Save the answer to the variable final_grade.
'''
final_grade = total_grade/3
final_grade

array([86.        , 93.        , 82.        , 91.33333333, 90.        ])