In [1]:
import numpy as np

In [3]:
'''
Imagine you’re a teacher and you need to keep track of your student’s test scores. On the first test, the students received the following scores:
92, 94, 88, 91, 87
Create a NumPy array with these values and save it with the name test_1.
'''

test1 = np.array([92, 94, 88, 91, 87])
test1

array([92, 94, 88, 91, 87])

In [4]:
#Most of the times, we usually get the values from a file. Numpy gives
#a function called genfromtxt which delimeter as a paramter thro which
#we can import the data into a numpy array

test2 = np.genfromtxt('samplefile.csv',delimiter=',') #you can use any other delimeter that seperates the values
print(test2)

[10. 20. 30. 40. 50.]


In [5]:
#So what makes Numpy so special, it eliminates the use of for loop
'''
If we wanted to add 3 to each element of the list in python
list1 = [1,3,4,5]
list_add_3 = []
for i in range(len(list1)):
  list_add_3.append(list1[i] + 3)
'''
#The same above code in numpy would become
list1 = [1,3,4,5]
nplist1 = np.array(list1)
nplist1 = nplist1 +3 #This is the element row wise operation.
#We can do the same thing for all mathematical operations
print(nplist1)

[4 6 7 8]


In [7]:
#Similarly we can do any mathematical operation the numpy arrays together if they are of equal length

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
'''
Let’s find the average of each student’s test scores to calculate their final
grade for the semester. Start by adding the three arrays together and
save the answer to the variable total_grade.
'''
total_grade = test_1 + test_2 + test_3
total_grade

array([258, 279, 246, 274, 270])

In [8]:
'''
Now, divide total_grade by the number of tests taken to find the average score
for each student. Save the answer to the variable final_grade.
'''
final_grade = total_grade/3
final_grade

array([86.        , 93.        , 82.        , 91.33333333, 90.        ])

Below wont work as the length of both the lists sent in are not similar

In [9]:
#Let us test some scenarios to ensure that we understand 2 dimensional arrays

array_1 = np.array([[1,2,3],[1,2]])
array_1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Below wont work as the outer square brackets were missing

In [11]:
array_3 = np.array([1,2,3],[4,5,6])
array_3

TypeError: Field elements must be 2- or 3-tuples, got '4'

This would work as the declaration and the number of elements are the same.

In [10]:
array_2 = np.array([[1,2,3],[4,5,6]])
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
'''
.
In statistics, we often use two-dimensional arrays to represent a set of samples.
For instance, if we flip a coin we can represent each head as a 1 and each tail as a 0.
Create a one-dimensional array for a coin toss experiment that results in heads,
tails, tails, heads, tails, and save it to the variable coin_toss.
'''
coin_toss = np.array([1,0,0,1,0])

#We run the experiment again and get the following outcome: tails, tails, heads,
#heads, heads. Create a new array that represents both outcomes as a single
#experiment. Save the new array to coin_toss_again.

coin_toss_again = np.array([coin_toss,[0,0,1,1,1]])
coin_toss_again

array([[1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1]])

In [14]:
'''
	     Tanya	Manual	Adwoa	Jeremy	Cody
test_1	92	94	88	91	87
test_2	79	100	86	93	91
test_3	87	85	72	90	92
'''

test_1 = np.array([92,84,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

'''
Jeremy wants to know what he scored on the second test.
Select the score from the test_2 array and save it to the variable jeremy_test_2.
'''
jeremy_test_2 = test_2[-2]
jeremy_test_2

np.int64(93)

In [15]:
'''
You want to compare how Manual and Adwoa did on the first test.
Select both of their scores and save them in an array named manual_adwoa_test_1.
'''
manual_adwoa_test_1 = test_1[1:3]
manual_adwoa_test_1

array([84, 88])

In [19]:
#Selecting from a 2D Array
a = np.array([[32, 15, 6, 9, 14],
              [12, 10, 5, 23, 1],
              [2, 16, 13, 40, 37]])

# -> Select 16 from the above

a[2,1]

np.int64(16)

In [20]:
#Select the entire 3rd column
a[:,2]

array([ 6,  5, 13])

In [21]:
#Select the entire 2rd row
a[1,:]

array([12, 10,  5, 23,  1])

In [24]:
'''
	     Tanya	Manual	Adwoa	Jeremy	Cody
test_1	92	94	88	91	87
test_2	79	100	86	93	91
test_3	87	85	72	90	92

'''
student_scores = np.array([[92, 94, 88, 91, 87],
                           [79, 100, 86, 93, 91],
                           [87, 85, 72, 90, 92]])

'''
Tanya wants to know how well she did on third test. Select her score from the
array and save it to tanya_test_3.
'''
tanya_test_3 = student_scores[2,0]
print(tanya_test_3)

87


In [ ]:
'''
You have a parent teacher conference with Cody’s parents coming up and would
like to have all of his test scores handy.
Select all of Cody’s test scores and save them to a new array cody_test_scores.
'''

In [25]:
cody_test_scores = student_scores[:,-1]
print(cody_test_scores)

[87 91 92]
